Repository 2024-Techeer-Winter-BootCamp-Team-I/Backend, pull requests merged in 2025-01, with the labels that each got.

#6 [chore] MYSQL 세팅 설정
  Dockerfile
  config/settings.py
  docker-compose.yml
  requirements.txt
Labels: 🧭 Chore

#8 [chore] 젠킨스 파이프라인 세팅 완료
  Jenkinsfile
Labels: 🧭 Chore

#10 [fix] 젠킨스 파이프라인 주석오류 제거
  Jenkinsfile
Labels: 🏷 Fix

#12 [fix] jenkins 파이프라인 브랜치경로 재수정 완료
  Jenkinsfile
Labels: 🏷 Fix, 🧭 Chore

#15 [fix] mysql 데이터베이스 세팅 재설정
  config/settings.py
  requirements.txt
Labels: 🏷 Fix

#17 [fix] mysql 데이터베이스 도커, 로컬 재설정완료
  config/settings.py
Labels: 🏷 Fix

#21 [feat] AI 문서화 생성 기능 완료
  Dockerfile
  config/settings.py
  config/urls.py
  docker-compose.yml
  document/__init__.py
  document/admin.py
  document/apps.py
  document/migrations/0001_initial.py
  document/migrations/0002_alter_document_requirements.py
  document/migrations/__init__.py
  document/models.py
  document/serializers.py
  document/tests.py
  document/urls.py
  document/views.py
  requirements.txt
Labels: 🧭 Chore

#26 AI 문서화 수정 기능완료
  config/urls.py
  document/serializers.py
  document/urls.py
  document/views.py
Labels: 🧭 Chore

#30 [feat] AI 설계 생성 기능 구현완료
  docker-compose.yml
  document/serializers.py
  document/urls.py
  document/views.py
Labels: 🧭 Chore

#34 [feat] AI 문서화 조회 기능완료
  document/urls.py
  document/views.py
Labels: 🧭 Chore

#45 [refactor] AI 문서화 기능 SSE 통신 기능 완료
  document/views.py
Labels: 🚀 Feat

#56 [feat] 로그인 시 jwt토큰과 refresh토큰 생성 후 클라이언트의 쿠키에 저장 기능 완료
  login/serializers.py
  login/templates/login/home.html
  login/templates/login/index.html
  login/urls.py
  login/views.py
Labels: 🚀 Feat

#68 [chore] 배포 서버 host 추가, Open AI 오류 해결
  config/settings.py
  document/views.py
Labels: 🏷 Fix, 🧭 Chore

#69 feat: jwt토큰 스웨거에서 인증 기능 구현 완료
  config/settings.py
  document/views.py
  login/models.py
  login/urls.py
  login/views.py
Labels: 🚀 Feat

#77 [refactor] AI 문서화 생성 구조 변경
  config/settings.py
  document/views.py
Labels: 🚀 Feat, 🏷 Fix

#79 [refactor] AI 문서화 수정기능 변경 + API 명세 리팩토링 완료
  document/serializers.py
  document/urls.py
  document/views.py
Labels: 🚀 Feat, 🏷 Fix

#81 [feat] 로그인 후 마이페이지 구현 완료
  document/views.py
  login/models.py
  login/serializers.py
  login/urls.py
  login/views.py
Labels: 🚀 Feat

#83 [refactor] API 명세(repo, directory) 리팩토링
  config/urls.py
  directory/urls.py
  repo/urls.py
Labels: 🚀 Feat

#89 [refactor] AI 문서화 스트리밍 방식 리팩토링
  document/views.py
Labels: 🚀 Feat

#92 [refactor] AI 설계 생성 구조 리팩토링 완료
  document/tasks.py
  document/views.py
Labels: 🏷 Fix, 🧭 Chore

#96 [feat] 마이페이지 프로젝트 확인 기능 구현, 로그인 앱 API 명세 리팩토링
  login/urls.py
  login/views.py
Labels: 🚀 Feat

#104 [refactor] user모델 수정 및 api연동 시 변경되는 코드 주석문으로 추가
  document/views.py
  login/models.py
  login/views.py
Labels: 🚀 Feat

#109 [feat] 마이페이지에서 프로젝트 삭제 기능 추가
  login/views.py
Labels: 🚀 Feat

#111 사용자 프로젝트 컨테이너 생성 기능(Docker in Docker)
  config/settings.py
  config/urls.py
  dind/__init__.py
  dind/admin.py
  dind/apps.py
  dind/migrations/__init__.py
  dind/models.py
  dind/serializers.py
  dind/tests.py
  dind/urls.py
  dind/view.py
  docker-compose.yml
  document/views.py
  requirements.txt
Labels: 🚀 Feat

#114 [docs] 설계 swagger 문서 변경
  document/views.py
Labels: 📑 Docs

#116 [docs] 설계 파트 문서 수정
  document/views.py
Labels: 📑 Docs

#120 [chore] cors 설정 추가완료
  config/settings.py
  document/tasks.py
  requirements.txt
Labels: 🧭 Chore

#122 [fix] cors 환경 설정 에러 수정
  config/settings.py
Labels: 🏷 Fix

#124 [refactor] Jenkinsfile 수정
  Jenkinsfile
Labels: 🚀 Feat

#126 [fix] jenkins 파일 재수정
  Jenkinsfile
Labels: 🏷 Fix

#129 [feat] 프롬프팅 1차 기능 개선
  document/tasks.py
  document/views.py
Labels: 🚀 Feat

#131 [fix] Jenkins docker-hub 로그인 수정
  Jenkinsfile
Labels: 🏷 Fix

#133 [fix] Jenkins docker-hub 로그인 재수정
  Jenkinsfile
Labels: 🏷 Fix

#136 [fix] Jenkins repository 경로 수정
  Jenkinsfile
Labels: 🏷 Fix

#137 [feat] 프롬프팅 2차 수정
  document/tasks.py
  document/views.py
  login/urls.py
Labels: 🚀 Feat

#139 [feat] 로그인 시 클라이언트의 쿠기에 저장되도록 수정
  config/settings.py
  login/views.py
Labels: 🚀 Feat

#141 [fix] 도커인도커 데몬 실패 오류 수정
  dind/view.py
Labels: 🏷 Fix

#144 [feat] 깃허브 아이디와 프로필 이미지를 전송하는 api 생성
  login/urls.py
  login/views.py
Labels: 🚀 Feat

#147 [feat] jwt토큰 만료 시 재발급
  login/urls.py
  login/views.py
Labels: 🚀 Feat

#153 [chore] https 설정
  config/settings.py
Labels: 🧭 Chore

#156 [refactor] settings 데이터베이스 getenv 수정
  config/settings.py
Labels: 🚀 Feat

#157 [feat] 로그인 시 이메일 받기 및 3차 프롬프팅
  document/tasks.py
  login/serializers.py
  login/views.py
Labels: 🚀 Feat

#159 [refactor] 문서생성 response body document_id 추가
  document/views.py
Labels: 🚀 Feat

#166 [refactor] 스트리밍 방식 document_id 로직 변경
  document/views.py
Labels: 🚀 Feat

#169 [refactor] docker in docker 비동기 처리 구현
  dind/tasks.py
  dind/urls.py
  dind/view.py
Labels: 🚀 Feat

#171 [fix] dind 비동기 처리 urls 이름 수정
  dind/urls.py
  dind/view.py
Labels: 🏷 Fix

#173 [refactor] 문서화 수정 기능 스트리밍 방식 리팩토링
  document/views.py
Labels: 🚀 Feat

#175 [chore] CORS_ALLOWED_ORIGINS 추가 설정
  config/settings.py
Labels: 🧭 Chore

#182 [refactor] 문서생성, 문서수정 SSE 통신 리팩토링
  document/views.py
Labels: 🚀 Feat

#187 [chore] 모니터링(Grafana + Prometeus) 설정 추가
  .gitignore
  config/settings.py
  config/urls.py
  dind/tasks.py
  docker-compose.yml
  prometheus/prometheus.yml
  requirements.txt
Labels: 🧭 Chore

#189 [refactor] 문서화 스트리밍 구조 분할 리팩토링
  document/urls.py
  document/views.py
Labels: 🚀 Feat

#191 [fix] 문서화 response_body id값 수정
  document/views.py
Labels: 🚀 Feat, 🏷 Fix

#193 [refactor] 문서화 스트리밍 데이터 형식 수정
  document/views.py
Labels: 🚀 Feat

#196 [feat] 마이페이지 document_id전달
  login/serializers.py
  login/views.py
Labels: 🚀 Feat

#200 [refactor] 문서 수정 스트리밍 SSE 리팩토링
  document/urls.py
  document/views.py
Labels: 🚀 Feat

#206 [refactor] 배포서버 호스트 수정
  config/settings.py
Labels: 🚀 Feat

#208 [feat] openai로 llm 변경
  Tech_Stack/tasks.py
  docker-compose.yml
  document/tasks.py
  document/views.py
Labels: 🚀 Feat

#212 [feat] 초기세팅 프롬프팅 기능개선
  Tech_Stack/tasks.py
Labels: 🚀 Feat

#215 [fix] sse 코드 오타 에러 수정
  document/views.py
Labels: 🏷 Fix

#217 [refactor] 문서 스트리밍 open ai 변경 리팩토링
  config/settings.py
  document/views.py
Labels: 🚀 Feat

#220 [refactor] 문서수정 스트리밍 open ai 변경 리팩토링
  document/views.py
Labels: 🚀 Feat

#225 [fix] 문서생성 스트리밍 postman SSE 코드 수정
  document/views.py
Labels: 🏷 Fix

#229 [refactor] 문서생성 스트리밍 postman SSE 코드 수정
  document/views.py
Labels: 🚀 Feat

#231 [refactor] 문서생성, 수정 SSE 줄바꿈 추가
  document/views.py
Labels: 🚀 Feat

#236 [refactor]레포지토리 푸시 수정
  repo/tasks.py
Labels: 🚀 Feat

#247 [refactor] dind docker-compose.yml 경로 리팩토링
  dind/view.py
Labels: 🚀 Feat

#250 [refactor] ERD, Diagram 프롬프트 리팩토링
  document/tasks.py
Labels: 🚀 Feat

#251 [feat] 초기세팅 오류해결
  Tech_Stack/tasks.py
  Tech_Stack/utils.py
  Tech_Stack/views.py
Labels: 🚀 Feat, 🏷 Fix

#253 [feat] 초기세팅 비동기 처리 구현
  Tech_Stack/tasks.py
  Tech_Stack/views.py
Labels: 🚀 Feat
